<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 6.10 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.10</h1>
<h3>Interface für Injektion von Pizzaböden aus Weizenmehl</h3>
<pre>
&lt;?php 
namespace Pizza;

interface WheatFlourAwareInterface
{
    public function setWheatFlourCrust($crust);
    
    public function getWheatFlourCrust();
}
</pre>
</div>
</div>
