<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.14 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.14</h1>
<h3>Abstract Factory für die Erstellung von Pizzabelägen</h3>
<pre>
&lt;?php 
namespace Pizza;

use Zend\ServiceManager\AbstractFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class ToppingAbstractFactory implements AbstractFactoryInterface
{
    public function canCreateServiceWithName(ServiceLocatorInterface $serviceLocator, 
        $name, $requestedName
    ) {
        if (class_exists($this->getClassName($requestedName))) {
            return true;
        }
        
        return false;
    }
    
    public function createServiceWithName(ServiceLocatorInterface $serviceLocator, 
        $name, $requestedName
    ) {
        $class = $this->getClassName($requestedName);
        
        $instance = new $class;
        
        if ($instance instanceof ToppingInterface) {
            return $instance;
        }
        
        return false;
    }
    
    protected function getClassName($requestedName)
    {
        $parts = split('-', $requestedName);
        
        return __NAMESPACE__ . '\\' . $parts[1];
    }
}
</pre>
</div>
</div>
