<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 6.22 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.22</h1>
<h3><code>Zend\Di</code> mit Konfigurationsdatei verwenden</h3>
<pre>
&lt;?php 
// namespaces
use Zend\Debug\Debug;
use Zend\Di\Config;
use Zend\Di\Di;

// create configuration
$config = new Config(include LUIGI_ROOT . '/module/Pizza/config/di.config.php');

// configure dependency injection container
$di = new Di();
$di->configure($config);

// get pizza melon
$pizzaMelon = $di->get('Pizza\Entity\PizzaMelon');

// output pizza
Debug::dump($pizzaMelon);
</pre>
<h3>Ausgabe</h3>
<?php 
// namespaces
use Zend\Debug\Debug;
use Zend\Di\Config;
use Zend\Di\Di;

// create configuration
$config = new Config(include LUIGI_ROOT . '/module/Pizza/config/di.config.php');

// configure dependency injection container
$di = new Di();
$di->configure($config);

// get pizza melon
$pizzaMelon = $di->get('Pizza\Entity\PizzaMelon');

// output pizza
Debug::dump($pizzaMelon);
?>
</div>
</div>
