<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 6.11 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.11</h1>
<h3>Pizza Salami Klasse implementiert <code>WheatFlourAwareInterface</code></h3>
<pre>
&lt;?php
namespace Pizza\Entity;

use Pizza\Crust\WheatFlourAwareInterface;

class PizzaSalami implements WheatFlourAwareInterface
{
    protected $id    = 1101;
    protected $name  = 'Pizza Salami';
    protected $price = 6.95;
    protected $crust = null;
    
    public function setWheatFlourCrust($crust)
    {
        $this->crust = $crust;
    }
    
    public function getWheatFlourCrust()
    {
        return $this->crust;
    }
}
</pre>
</div>
</div>
