<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.3</h1>
<h3>Serviceklasse für den Pizza-Service</h3>
<pre>
&lt;?php 
namespace Pizza\Service;

use Pizza\Entity\Pizza as PizzaEntity;
use Pizza\Form\PizzaCreate;

class Pizza
{
    protected $createForm = null;
    protected $entity     = null;
    
    public function __construct(PizzaCreate $createForm, PizzaEntity $entity)
    {
        $this->setCreateForm($createForm);
        $this->setEntity($entity);
    }
    
    public function setCreateForm(PizzaCreate $createForm)
    {
        $this->createForm = $createForm;
    }
    
    public function getCreateForm()
    {
        return $this->createForm;
    }

    public function setEntity(PizzaEntity $entity)
    {
        $this->entity = $entity;
    }
    
    public function getEntity()
    {
        return $this->entity;
    }
}
</pre>
</div>
</div>
