<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.12</h1>
<h3>Programmatische Konfiguration vom Service-Manager mit Initializer</h3>
<pre>
&lt;?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\ServiceManager;
use Pizza\Crust\WheatFlourAwareInterface;

// initialize service manager
$serviceManager = new ServiceManager();

// configure service manager
$serviceManager->setInvokableClass('Crust\WheatFlour', 'Pizza\Crust\WheatFlour');
$serviceManager->setInvokableClass('Pizza\Salami', 'Pizza\Entity\PizzaSalami');
$serviceManager->addInitializer(function ($instance) use ($serviceManager) {
    if ($instance instanceof WheatFlourAwareInterface) {
        $instance->setWheatFlourCrust($serviceManager->get('Crust\WheatFlour'));
    }
});

// output some classes
Debug::dump($serviceManager->get('Crust\WheatFlour'));
Debug::dump($serviceManager->get('Pizza\Salami'));
</pre>
<h3>Ausgabe</h3>
<?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\ServiceManager;
use Pizza\Crust\WheatFlourAwareInterface;

// initialize service manager
$serviceManager = new ServiceManager();

// configure service manager
$serviceManager->setInvokableClass('Crust\WheatFlour', 'Pizza\Crust\WheatFlour');
$serviceManager->setInvokableClass('Pizza\Salami', 'Pizza\Entity\PizzaSalami');
$serviceManager->addInitializer(function ($instance) use ($serviceManager) {
    if ($instance instanceof WheatFlourAwareInterface) {
        $instance->setWheatFlourCrust($serviceManager->get('Crust\WheatFlour'));
    }
});

// output some classes
Debug::dump($serviceManager->get('Crust\WheatFlour'));
Debug::dump($serviceManager->get('Pizza\Salami'));
?>
</div>
</div>
