<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.15 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.15</h1>
<h3>Programmatische Konfiguration für Service-Manager mit <code>AbstractFactory</code></h3>
<pre>
&lt;?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Exception\ServiceNotFoundException;
use Pizza\Topping\ToppingAbstractFactory;

// initialize service manager
$serviceManager = new ServiceManager();

// configure service manager
$serviceManager->addAbstractFactory(new ToppingAbstractFactory());

// output some classes
Debug::dump($serviceManager->get('Topping-Cheese'));
Debug::dump($serviceManager->get('Topping-Salami'));

try {
    Debug::dump($serviceManager->get('Topping-Pineapple'));
} catch (ServiceNotFoundException $e) {
    echo 'Ananas ist gerade aus.';
}
</pre>
<h3>Ausgabe</h3>
<?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Exception\ServiceNotFoundException;
use Pizza\Topping\ToppingAbstractFactory;

// initialize service manager
$serviceManager = new ServiceManager();

// configure service manager
$serviceManager->addAbstractFactory(new ToppingAbstractFactory());

// output some classes
Debug::dump($serviceManager->get('Topping-Cheese'));
Debug::dump($serviceManager->get('Topping-Salami'));

try {
    Debug::dump($serviceManager->get('Topping-Pineapple'));
} catch (ServiceNotFoundException $e) {
    echo '<pre>Ananas ist gerade aus.</pre>';
}
?>
</div>
</div>
