<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 6.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.8</h1>
<h3>Initialisierung vom Service-Manager mit Konfigurationsdatei</h3>
<pre>
&lt;?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\Config;
use Zend\ServiceManager\ServiceManager;

// create service configuration
$config = new Config(
    include LUIGI_ROOT . '/module/Pizza/config/service.config.php'
);

// configure service manager
$serviceManager = new ServiceManager($config);

// output some classes
Debug::dump($serviceManager->get('CreateForm'));
Debug::dump($serviceManager->get('Pizza\Service'));
Debug::dump($serviceManager->get('Entity'));
Debug::dump($serviceManager->get('Entity'));
</pre>
<h3>Ausgabe</h3>
<?php 
// namespaces
use Zend\Debug\Debug;
use Zend\ServiceManager\Config;
use Zend\ServiceManager\ServiceManager;

// create service configuration
$config = new Config(
    include LUIGI_ROOT . '/module/Pizza/config/service.config.php'
);

// configure service manager
$serviceManager = new ServiceManager($config);

// output some classes
Debug::dump($serviceManager->get('CreateForm'));
Debug::dump($serviceManager->get('Pizza\Service'));
Debug::dump($serviceManager->get('Entity'));
Debug::dump($serviceManager->get('Entity'));
?>
</div>
</div>
