<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.17 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.17</h1>
<h3>Automatische Erkennung von Abhängigkeiten mit <code>Zend\Di</code></h3>
<pre>
&lt;?php 
// namespaces
use Zend\Debug\Debug;
use Zend\Di\Di;
use Zend\Math\Rand;

// configure dependency injection container
$di = new Di();
$di->instanceManager()->setParameters(
    'Pizza\Entity\PizzaMelon', 
    array(
        'id'    => Rand::getInteger(100, 199),
        'name'  => 'Pizza Melone',
        'price' => round(Rand::getFloat() + 6, 2),
    )
);

// get pizza melon
$pizzaMelon = $di->get('Pizza\Entity\PizzaMelon');

// output pizza
Debug::dump($pizzaMelon);
</pre>
<h3>Ausgabe</h3>
<?php 
// namespaces
use Zend\Debug\Debug;
use Zend\Di\Di;
use Zend\Math\Rand;

// configure dependency injection container
$di = new Di();
$di->instanceManager()->setParameters(
    'Pizza\Entity\PizzaMelon', 
    array(
        'id'    => Rand::getInteger(100, 199),
        'name'  => 'Pizza Melone',
        'price' => round(Rand::getFloat() + 6, 2),
    )
);

// get pizza melon
$pizzaMelon = $di->get('Pizza\Entity\PizzaMelon');

// output pizza
Debug::dump($pizzaMelon);
?>
</div>
</div>
