<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.2</h1>
<h3>Formularklasse zum Anlegen einer Pizza</h3>
<pre>
&lt;?php 
namespace Pizza\Form;

class PizzaCreate
{
    protected $elements = array(
        'id',
        'name',
        'price',
    );
}
</pre>
</div>
</div>
