<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 6.13 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 6.13</h1>
<h3>Klassen und Interface für Pizzabeläge</h3>
<pre>
&lt;?php 
namespace Pizza\Topping;

interface ToppingInterface {}

class Cheese implements ToppingInterface
{
    protected $name = 'Käse';
}

class Melon implements ToppingInterface
{
    protected $name = 'Melone';
}

class Salami implements ToppingInterface
{
    protected $name = 'Salami';
}

class TomatoStodge implements ToppingInterface
{
    protected $name = 'Tomatenpampe';
}
</pre>
</div>
</div>
