<?php 
/**
 * ZF2 Buch Kapitel 6
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 6</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0601">Listing 6.1</a></td>
<td>Entitätsklasse für eine Pizza</td>
</tr>
<tr>
<td><a href="/listing/listing0602">Listing 6.2</a></td>
<td>Formularklasse zum Anlegen einer Pizza</td>
</tr>
<tr>
<td><a href="/listing/listing0603">Listing 6.3</a></td>
<td>Serviceklasse für den Pizza-Service</td>
</tr>
<tr>
<td><a href="/listing/listing0604">Listing 6.4</a></td>
<td>Factory-Klasse für Serviceklasse des Pizza-Services</td>
</tr>
<tr>
<td><a href="/listing/listing0605">Listing 6.5</a></td>
<td>Konfigurationsklasse für den Service-Manager</td>
</tr>
<tr>
<td><a href="/listing/listing0606">Listing 6.6</a></td>
<td>Initialisierung vom Service-Manager mit Konfigurationsklasse</td>
</tr>
<tr>
<td><a href="/listing/listing0607">Listing 6.7</a></td>
<td>Konfigurationsdatei für den Service-Manager</td>
</tr>
<tr>
<td><a href="/listing/listing0608">Listing 6.8</a></td>
<td>Initialisierung vom Service-Manager mit Konfigurationsdatei</td>
</tr>
<tr>
<td><a href="/listing/listing0609">Listing 6.9</a></td>
<td>Klasse für Pizzaboden aus Weizenmehl</td>
</tr>
<tr>
<td><a href="/listing/listing0610">Listing 6.10</a></td>
<td>Interface für Injektion von Pizzaböden aus Weizenmehl</td>
</tr>
<tr>
<td><a href="/listing/listing0611">Listing 6.11</a></td>
<td>Pizza Salami Klasse implementiert <code>WheatFlourAwareInterface</code></td>
</tr>
<tr>
<td><a href="/listing/listing0612">Listing 6.12</a></td>
<td>Programmatische Konfiguration vom Service-Manager mit Initializer</td>
</tr>
<tr>
<td><a href="/listing/listing0613">Listing 6.13</a></td>
<td>Klassen und Interface für Pizzabeläge</td>
</tr>
<tr>
<td><a href="/listing/listing0614">Listing 6.14</a></td>
<td>Abstract Factory für die Erstellung von Pizzabelägen</td>
</tr>
<tr>
<td><a href="/listing/listing0615">Listing 6.15</a></td>
<td>Programmatische Konfiguration für Service-Manager mit <code>AbstractFactory</code></td>
</tr>
<tr>
<td><a href="/listing/listing0616">Listing 6.16</a></td>
<td>Pizza Melone Klasse mit Konstruktor und Settern</td>
</tr>
<tr>
<td><a href="/listing/listing0617">Listing 6.17</a></td>
<td>Automatische Erkennung von Abhängigkeiten mit <code>Zend\Di</code></td>
</tr>
<tr>
<td><a href="/listing/listing0618">Listing 6.18</a></td>
<td>Definitionsliste für <code>Zend\Di</code> automatisch compilieren</td>
</tr>
<tr>
<td><a href="/listing/listing0619">Listing 6.19</a></td>
<td>Ausschnitt aus der kompilierten Definitionliste für <code>Zend\Di</code></td>
</tr>
<tr>
<td><a href="/listing/listing0620">Listing 6.20</a></td>
<td><code>Zend\Di</code> mit kompilierter Definitionsliste verwenden</td>
</tr>
<tr>
<td><a href="/listing/listing0621">Listing 6.21</a></td>
<td>Konfigurationsdatei für <code>Zend\Di</code></td>
</tr>
<tr>
<td><a href="/listing/listing0622">Listing 6.22</a></td>
<td><code>Zend\Di</code> mit Konfigurationsdatei verwenden</td>
</tr>
</tbody>
</table>
